apiVersion: v1
kind: Secret
metadata:
   name: {{ include "youtube-stats-chart.fullname" . }}-secrets
type: Opaque
data:
  YOUTUBE_API_KEY: {{ .Values.youtubeStatsSettings.ytAPIKey | default "" | b64enc | quote}}
  YOUTUBE_ID: {{ .Values.youtubeStatsSettings.ytId | default "" | b64enc | quote}}